export enum EStateKeys {
  PHONE = 'phone',
  LAST_NAME = 'last_name',
  FIST_NAME = 'first_name',
  MIDDLE_NAME = 'middle_name',
  IIN = 'iin',
  DOCUMENT_NUMBER = 'document_number',
  DOCUMENT_ISSUED_AT = 'document_issued_at',
  DOCUMENT_ISSUED_BY = 'document_issued_by',
  CITY = 'city',
  ADDRESS = 'address',
  BANK_NAME = 'bank_name',
  IBAN = 'iban',
  CODE = 'code',
  DOCUMENT_FILES = 'document_files',
  VACCINE_PASSPORT_FILES = 'vaccine_passport_files',
  MEDICAL_PASSPORT_FILES = 'medical_passport_files',
  BADGE_FILES = 'badge_files',
}
